site_name: Bedrock DebugInfo
site_url: https://bedrockdebug.info/
repo_url: https://github.com/liteldev-free/DebugInfo
edit_uri: edit/main/docs/
repo_name: liteldev-free/DebugInfo
nav:
  - Home:
      - index.md
      - releases.md
      - FAQ: faq.md
      - License: license.md
  - Toolchain:
      - toolchain/index.md
      - toolchain/DeThunk.md
      - toolchain/DumpSYM.md
      - toolchain/ExtractSYM.md
      - toolchain/AskRVA.md
      - toolchain/MakePDB.md
      - toolchain/BlobExtractor.md
  - Tutorial:
      - Generate a PDB from scratch: tutorial/generate-a-pdb-from-scratch.md
  - Research:
      - research/index.md
      - research/HeaderGen.md
      - research/PreLoader.md
      - research/FakeSymbol.md
  - Community:
      - community/index.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Contribution Guidelines: CONTRIBUTING.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  icon:
    annotation: material/arrow-right-circle
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
  - git-committers:
      enabled: true
      repository: liteldev-free/DebugInfo
      branch: main
extra:
  alternate:
    - name: English
      link: /
      lang: en
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liteldev-free
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fPKVZScPT7
    - icon: fontawesome/brands/telegram
      link: https://t.me/s/bdsplugins
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; 2025 - present Open LiteLDev
