name: Build (MacOS)

on:
  push:
    paths:
      - .github/workflows/build_macos.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mode: [release, debug]
        arch: [arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore xmake cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
            ./.xmake-dest
          key: xmake-macos-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-macos-

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.9"
          actions-cache-folder: "./.xmake-dest"

      - name: Configure
        run: |
          xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -p macosx -vD -y

      # - name: Build
      #   run: |
      #     xmake -vD -y

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debuginfo-macosx-${{ matrix.arch }}-${{ matrix.mode }}
          path: |
            build/macosx/${{ matrix.arch }}/${{ matrix.mode }}
