name: Build (MacOS)

on:
  push:
    paths:
      - .github/workflows/build-macos.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mode: [release, debug]
        arch: [arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Setup LLVM
        run: |
          brew install llvm

      - name: Restore Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-macos-${{ matrix.arch }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-macos-${{ matrix.arch }}-

      - name: Configure
        run: |
          xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -p macosx -v -y

      - name: Build
        run: |
          xmake -v -y

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debuginfo-macosx-${{ matrix.arch }}-${{ matrix.mode }}
          path: |
            build/macosx/${{ matrix.arch }}/${{ matrix
.mode }}
